In [1]:
import numpy as np
import matplotlib.pyplot as plt

1. Gauss Elimination
1. LU Factorization, matrix inversion 
2. Solution by iteration (Gauss-Seidel)
3. Ill-conditioning, norms

LAB:


# Numeric Linear Algebra
This chapter discuss how to solve linear systems of equations numerically. We start with Gauss elimination, which are similar to how human being solving linear equations on the paper. We will also discuss several variants of this method (Doolittle, Cholesky, Gauss-Jordan). Then we will introduce numeric iteration methods to address the problem. These methods are less intuitive, but more computational effective and much more frequently used nowadays. 

## Gauss Elimination
Gauss elimination and back substitution are common methods to solve linear equation set using matrix method. A **linear system of $n$ equations** in $n$ unknowns $x_1,...,x_n$ is a set of equations of the form
$$
a_{11}x_1 + ... a_{1n}x_n = b_1 \\
a_{21}x_1 + ... a_{2n}x_n = b_2 \\
... .........\\
a_{n1}x_1 + ... a_{nn}x_n = b_n
$$
where the **coefficient** $a_{jk}$ and the $b_j$ are given numbers. This equation set can be written in matrix form as
$$ Ax=b $$
where the **coefficient matrix** $A=[a_{jk}]$ is the $n \times n$ matrix, $x$ and $b$ are $n\times 1$ vectors.
$$
A = 
\left[
\begin{matrix}
a_{11} & a{12} & ... & a_{1n} \\
a_{21} & a{22} & ... & a_{2n} \\
. & . & . & . \\
a_{n1} & a{n2} & ... & a_{nn}
\end{matrix} \right], \ \ x=
\left[
\begin{matrix}
x_1 \\ x_2 \\ \vdots \\ x_n
\end{matrix}
\right], \ \ b=
\left[
\begin{matrix}
b_1 \\ b_2 \\ \vdots \\ b_n
\end{matrix}
\right].
$$

We then form an **argmented matrix** of the system:
$$
\tilde{A} = [A\ b]=
\left[
\begin{matrix}
a_{11} & ... & a_{1n} & b_1 \\
a_{21} & ... & a_{2n} & b_2 \\
.&.&.&.\\
a_{n1} & ... & a_{nn} & b_n \\
\end{matrix}
\right].
$$
There are **three elementary row operations** we can perform on $\tilde A$ that will not change the solution of the linear equation system:
1. Interchange of two rows
2. Addition of a constant multiple of one row to another row
3. Multiplication of a row by a nonzero constant $c$

These three operations correspond to the following 
1. Interchange of two equations
2. Addition of a constant multiple of one equation to another euqation
3. Multiplication of an equation by a nonzero constant $c$

Gauss Elimination try to reduce the coefficient matrix $A$ from a full matrix to a **triangular** matrix through a combination of these three elementary row operations, which can then be easily solved by **back substitution**. For instance, a triangular system is
$$
\begin{align}
\hat a_{11} x_1 + \hat a_{12} x_2 + \hat a_{13} x_3 + ...+ \hat a_{1n} x_n &= \hat b_1 \\
\hat a_{22} x_2 + \hat a_{23} x_3 + ...+ \hat a_{2n} x_n &=\hat b_2 \\
\hat a_{33} x_3 + ... + \hat a_{3n} x_n &= \hat b_3 \\
...... \\
\hat a_{n-1 n-1} x_{n-1} + \hat a_{n-1n} x_n &=\hat b_{n-1} \\
\hat a_{nn} x_n &= \hat b_n
\end{align}
$$
Then from the last equation, we can solve the entire system step by step by **back substitution**:
$$
\begin{align}
x_n &= \frac{\hat b_n}{\hat a_{nn}} \\
x_{n-1} &= \frac{1}{\hat a_{n-1n-1}}(\hat b_{n-1} - \hat a_{n-1n}x_n) \\
& ...... \\
 x_1  &=\frac{1}{\hat a_{11}} (\hat b_1 - \hat a_{12} x_2 - \hat a_{13} x_3 - ...- \hat a_{1n} x_n)
\end{align}
$$

To transform coefficient matrix $A$ into a triangular form, we first eliminate coefficient of $x_1$ from row 2 to $n$ of $\tilde A$ by subtracting suitable multiples of row 1 from the other rows. In this step, the first row is called the **pivot equation** and $a_{11}$ is called the **pivot**. We changes all the rows of $\tilde A$ except for the pivot row. We then eliminate coefficient of $x_2$ from row 3 to $n$ by subtracting suitable multiples of row 2 from all the rows below, and so on. 
$$
\tilde{A_0} = 
\left[
\begin{matrix}
a_{11} & a_{12} & ... & a_{1n} & b_1 \\
a_{21} & a_{22} &... & a_{2n} & b_2 \\
.&.&.&.&.\\
a_{n1} & a_{n2} &... & a_{nn} & b_n 
\end{matrix}
\right].
$$

$$
\tilde{A_1} = 
\left[
\begin{matrix}
a_{11} & a_{12} & ... & a_{1n} & b_1 \\
a_{21} - a_{11}\frac{a_{21}}{a_{11}} & a_{22}- a_{12}\frac{a_{21}}{a_{11}} & ... 
& a_{2n} - a_{1n}\frac{a_{21}}{a_{11}} & b_2 - b_1\frac{a_{21}}{a_{11}} \\
.&.&.&.&.\\
a_{n1} - a_{11}\frac{a_{n1}}{a_{11}} & a_{n2}- a_{12}\frac{a_{n1}}{a_{11}} & ... 
& a_{nn} - a_{1n}\frac{a_{n1}}{a_{11}} & b_n - b_1\frac{a_{n1}}{a_{11}} 
\end{matrix}
\right]
=
\left[
\begin{matrix}
a_{11} & a_{12} & ... & a_{1n} & b_1 \\
0 & a_{22}^{(1)} &... & a_{2n}^{(1)} & b_2^{(1)} \\
.&.&.&.&.\\
0 & a_{n2}^{(1)} &... & a_{nn}^{(1)} & b_n^{(1)} 
\end{matrix}
\right]. 
$$

$$
\vdots 
$$
$$
\vdots 
$$

$$
\tilde A_n = 
\left[
\begin{matrix}
a_{11} & a_{12} &a_{13} & ... & a_{1n} & b_1 \\
0 & a_{22}^{(1)} &a_{23}^{(1)} &... & a_{2n}^{(1)} & b_2^{(1)} \\
0 & 0 & a_{33}^{(2)} &... & a_{3n}^{(2)} & b_2^{(2)} \\
.&.&.&.&.&.\\
0 & 0 & 0 &... & a_{nn}^{(n-1)} & b_n^{(n-1)} 
\end{matrix}
\right]. 
$$

One practical concern about Gauss Elimination is that the pivot $a_{kk}$ **must be** different from zero and **should be** large in absolute value to avoid numeric instability in the elimination. For this reason in each step we choose our pivot row the one with the absolutely largest $a_{jk}$ (with $j>k$) and interchange it with current row $k$. This method is called **partial pivoting** and is quite popular (e.g., Maple).

In [2]:
def Gauss_elimination(A,b,print_process=False):
    ''' Function that utilizes Gauss Elimination and back substitution to solve
    a linear system Ax = b
    usage: x = Gauss_elimination(A,b,print_process=False):
    input: 
        A: nxn coefficient matrix, full rank
        b: nx1 vector
        print_process: boolean, whether to print the step-by-step process 
                        for Gauss Elimination
    output:
        solution x
    written by Ge Jin, gjin@mines.edu, 06/2019
    '''
    n = A.shape[0]
    # generate argmented matrix
    Ab = np.hstack((A,b.reshape(-1,1)))
    # Gauss Elimination
    for k in range(n-1):
        # find the row with max ajk
        maxi = np.argmax(Ab[:,k])
        # swap the rows
        Ab[[k,maxi]] = Ab[[maxi,k]]
        # eliminate ajk from row k+1 to n
        for j in range(k+1,n):
            Ab[j,:] = Ab[j,:] - Ab[k,:]*Ab[j,k]/Ab[k,k]
        if print_process:
            print('Ab_{}='.format(k))
            print(Ab)

    # back substitution
    x = np.zeros(n)
    x[n-1] = Ab[n-1,n]/Ab[n-1,n-1]
    for k in range(len(x)-2,-1,-1):
        x[k] = 1/Ab[k,k]*(Ab[k,n]-np.sum(Ab[k,:-1]*x))
    return x

In [3]:
# an example
A = np.array([[6.,2,8],[3,5,2],[0,8,2]])
b = np.array([26.,8.,-7.])
x = Gauss_elimination(A,b,print_process=True)
print('x=',x)

Ab_0=
[[ 6.  2.  8. 26.]
 [ 0.  4. -2. -5.]
 [ 0.  8.  2. -7.]]
Ab_1=
[[ 6.   2.   8.  26. ]
 [ 0.   8.   2.  -7. ]
 [ 0.   0.  -3.  -1.5]]
x= [ 4.  -1.   0.5]


### Computation cost of Gauss Elimination
Generally, the important factors in judging the quality of a numeric method are
- Amount of storage
- Amount of time (number of operations)
- Effect of roundoff error (numerical stability)

For Gauss elimination, the operation count for a full matrix is as follows. In Step $k$ we eliminate $x_k$ from $n-k$ equations. This needs $n-k$ divisions in computing the $a_{jk}/a_{kk}$, and $(n-k)(n-k+1)$ multiplications and as many subtractions. Since we do $n-1$ steps, $k$ goes from 1 to $n-1$ and thus the total number of operations in this forward elimination is
$$
f(n) = \sum_{k=1}^{n-1}(n-k) + 2\sum_{k=1}^{n-1}(n-k)(n-k+1)
= \frac{1}{2}(n-1)n + \frac{2}{3}(n^2-1)n \approx \frac{2}{3} n^3
$$
where $2n^3/3$ is obtained by dropping lower powers of $n$ (when $n$ is large, the only term that matters is the one with highest power of $n$). Because $f(n)$ grows about proportional to $n^3$, we say that $f(n)$ is order $n^3$ and write
$$
f(n) = O(n^3)
$$

In the back substituion of $x_i$ we make $n-i$ multiplications and as many subtractions, as well as 1 division. Hence the number of operations in the back substitution is
$$
b(n) = 2\sum_{i=1}^{n}(n-i) + n = n(n+1)+n = N^2+2n = O(n^2)
$$

For instance, if an operation takes $10^{-9}$ second, then the times needed are:

| Algorithm | $n=1000$ | $n=10000$ |
|---------|-------------------|----------------|
|Elimination | 0.7 sec | 660 sec |
|Back substitution | 0.001 sec | 0.1 sec |


## LU-Factorization
Another way to solve linear systems $ Ax=b$ numerically if through **LU-Factorization**. An LU-factorization of a given square matrix $A$ is of the form
$$ A=LU $$
where $L$ is **lower triangular** matrix and $U$ is **upper triangular** matrix.

It can be proved that for any nonsingular matrix, the rows can be reordered so that the resulting matrix A has an LU-factorization in which $L$ turns out to be the matrix of the multipliers $m_{jk}$ of the Gauss elimination, with main diagonals equal 1, and $U$ is the matrix of the triangular system at the end of the Gauss elimination. 
$$
A = LU = 
\left[
\begin{matrix}
1 & 0 & 0 & ... & 0\\ 
m_{21} & 1 & 0  &...  &0 \\ 
m_{31} &m_{32}  &1  &...  &0 \\ 
\vdots &\vdots  &\vdots  &\vdots  &\vdots \\ 
m_{n1} &m_{n2}  &m_{n3}  &...  &1 
\end{matrix}
\right]
\left[
\begin{matrix}
u_{11} &u_{12}  &u_{13}  &...  &u{1n} \\ 
0 &u_{22}  &u_{23}  &...  &u_{2n} \\ 
0 &0  &u_{33}  &...  &u_{3n} \\ 
\vdots &\vdots  &\vdots  &\vdots  &\vdots \\ 
0 &0  &0  &...  &u_{nn} 
\end{matrix}
\right]
$$

And $L$ and $U$ can be calculated using **Doolittle method**:
$$
\begin{aligned}
u_{1k} &= a_{1k}  &k &= 1,...,n \\
m_{j1} &= \frac{a_{j1}}{u_{11}}  &j &=2,...,n \\
u_{jk} &= a_{jk} - \sum_{s=1}^{j-1} m_{js}u_{sk}   &k &=j,...,n;\;\; j \geq 2 \\
m_{jk} &= \frac{1}{u_{kk}} 
\left(
a_{jk} - \sum_{s=1}^{k-1} m_{js}u_{sk}
\right)   &j &=k+1,...,n; \;\; k\geq 2
\end{aligned}
$$

The crucial idea is that $L$ and $U$ can be computed directly, without solving simultaneous equations (thus, without suing the Gauss elimiantion). As a count shows, this needs about $n^3/3$ operations, about half as many as the Gauss elimination. Once we have $L$ and $U$, we can use it for solving $Ax=b$ in two steps, involving only about $n^2$ operations.

Noting that $Ax = LUx = b$ may be written as
$$
Ly = b \; \; \; where \; \; \; Ux=y
$$
We can use forward substitution to solve $y$, and then use backward substitution to solve $x$. 

A similar method, **Crout's method**, is obtained if $U$ (instead of $L$) is required to have main diagonals equal 1. In either case the factorization is unique.

### Exercise
1. Solve the LU factorization of a general $3 \times 3$ matrix 
$$
A = \left[
\begin{matrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} 
\end{matrix}
\right]
$$
2. **LAB**: write a function to calculate LU factorization of a $n \times n$ matrix, and count the number of operations numerically.

### Cholesky's Method
If matrix $A$ is symmetric and positive definite ($A=A^T,x^TAx > 0$ for all $x\neq0$), we can even choose $U=L^T$ to further reduce the computational cost. In this case, we cannot impose conditions on the main diagonal entries. 
$$
A = LL^T=
\left[
\begin{matrix}
l_{11} & 0 & 0 & ... & 0 \\
l_{21} & l_{22} & 0 & ... & 0 \\
l_{31} & l_{32} & l_{33} & ... & 0 \\
\vdots &\vdots &\vdots &\vdots &\vdots \\
l_{n1} & l_{n2} & l_{n3} & ... & l_{nn} 
\end{matrix}
\right]
\left[
\begin{matrix}
l_{11} & l_{21} & l_{31} & ... & l_{n1} \\
0 & l_{22} & l_{32} & ... & l_{n2} \\
0 & 0 & l_{33} & ... & l_{n3} \\
\vdots &\vdots &\vdots &\vdots &\vdots \\
0 & 0 & 0 & ... & l_{nn} 
\end{matrix}
\right]
$$

The formulas to calculate $l_{jk}$ are:
$$
\begin{aligned}
l_{11} &= \sqrt{a_{11}}  &  & \\
l_{j1} &= \frac{a_{j1}}{l_{11}}  &j &=2,...,n \\
l_{jj} &= \sqrt{a_{jj} - \sum_{s=1}^{j-1} l_{js}^2}   &j &=2,...,n \\
l_{pk} &= \frac{1}{l_{jj}} 
\left(
a_{pj} - \sum_{s=1}^{j-1} l_{js}l_{ps}
\right)   &p &=j+1,...,n; \;\; j\geq 2
\end{aligned}
$$

## Gauss-Jordan Elimination: Matrix Inversion
Sometimes it is useful to get the inversion of the matrix $A$, and **Gauss-Jordan elimination** is one of the methods calculate it. The inversion of a matrix is defined as
$$
AA^{-1} = A^{-1}A = I
$$
To get $A^{-1}$, similar to Gauss elimination, we can form the **argmented matrix**:
$$
\tilde{A} = [A\;I]=
\left[
\begin{matrix}
a_{11} & ... & a_{1n} & 1 & 0 & 0 & ... & 0 \\
a_{21} & ... & a_{2n} & 0 & 1 & 0 & ... & 0 \\
.&.&.&.&.&.&.&.\\
a_{n1} & ... & a_{nn} & 0 & 0 & 0 & ... & 1 \\
\end{matrix}
\right].
$$
We then apply the Gauss elimination to $\tilde A$, which gives a matrix of the form $[U \; H]$ with $U$ being an upper triangular matrix. The Gauss-Jordan method reduces U by further elementary row operations to diagonal form $[I\; K]$, where $K$ is the inversion of $A$. 

In [24]:
def gauss_jordan_matrix_inv(A,print_process=False):
    ''' Function that utilizes Gauss-Jordan Elimination 
    to calculate the inversion of the input matrix
    usage: x = gauss_jordan_matrix_inv(A,print_process=False):
    input: 
        A: nxn coefficient matrix, full rank
        print_process: boolean, whether to print the step-by-step process 
    output:
        inversion of A
    written by Ge Jin, gjin@mines.edu, 06/2019
    '''
    n = A.shape[0]
    step = 0
    # generate argmented matrix
    Ab = np.hstack((A,np.identity(n)))
    # Gauss Elimination
    for k in range(n-1):
        # find the row with max ajk
        maxi = np.argmax(Ab[:,k])
        # swap the rows
        Ab[[k,maxi]] = Ab[[maxi,k]]
        # eliminate ajk from row k+1 to n
        for j in range(k+1,n):
            Ab[j,:] = Ab[j,:] - Ab[k,:]*Ab[j,k]/Ab[k,k]
        if print_process:
            print('Ab_{}='.format(step))
            print(Ab)
            step += 1
    # change diagonal elements to 1 
    for k in range(n):
        Ab[k] /= Ab[k,k]
        if print_process:
            print('Ab_{}='.format(step))
            print(Ab)
            step += 1
    # Gauss-Jordan elimination
    for k in range(n-1,0,-1):
        for i in range(0,k):
            Ab[i] -= Ab[k]*Ab[i,k]
            if print_process:
                print('Ab_{}='.format(step))
                print(Ab)
                step += 1
    invA = Ab[:,n:]
    return invA


In [28]:
A = np.array([[-1,1,2],[3,-1,1],[-1,3,4]])
invA = gauss_jordan_matrix_inv(A,print_process=True)
print(invA)

Ab_0=
[[ 3.         -1.          1.          0.          1.          0.        ]
 [ 0.          0.66666667  2.33333333  1.          0.33333333  0.        ]
 [ 0.          2.66666667  4.33333333  0.          0.33333333  1.        ]]
Ab_1=
[[ 3.         -1.          1.          0.          1.          0.        ]
 [ 0.          2.66666667  4.33333333  0.          0.33333333  1.        ]
 [ 0.          0.          1.25        1.          0.25       -0.25      ]]
Ab_2=
[[ 1.         -0.33333333  0.33333333  0.          0.33333333  0.        ]
 [ 0.          2.66666667  4.33333333  0.          0.33333333  1.        ]
 [ 0.          0.          1.25        1.          0.25       -0.25      ]]
Ab_3=
[[ 1.         -0.33333333  0.33333333  0.          0.33333333  0.        ]
 [ 0.          1.          1.625       0.          0.125       0.375     ]
 [ 0.          0.          1.25        1.          0.25       -0.25      ]]
Ab_4=
[[ 1.         -0.33333333  0.33333333  0.          0.33333333  0. 